import os
import re
from typing import Optional, Dict, Any
from github import Github, PullRequest
import google.generativeai as genai

class GitHubClient:
    def __init__(self, token: str):
        self.gh = Github(token)

    def get_pr_details(self, repo_name: str, pr_number: int) -> Dict[str, Any]:
        repo = self.gh.get_repo(repo_name)
        pr = repo.get_pull(pr_number)
        
        # Get the files changed
        files_changed = []
        for file in pr.get_files():
            if not file.filename.endswith(('lock.json', '.svg', '.png')):
                files_changed.append({
                    "filename": file.filename,
                    "patch": file.patch or ""
                })
                
        # Get review comments if it was a code review
        reviews = pr.get_reviews()
        review_comments = [r.body for r in reviews if r.body and r.user.login == os.environ.get("GITHUB_ACTOR")]
        
        return {
            "title": pr.title,
            "body": pr.body or "",
            "files": files_changed,
            "review_comments": review_comments
        }

    def create_portfolio_pr(self, portfolio_repo_name: str, title: str, markdown_content: str) -> str:
        repo = self.gh.get_repo(portfolio_repo_name)
        
        # Create a new branch
        source_branch = repo.get_branch("master") # or main
        new_branch_name = f"draft-blog-{re.sub(r'[^a-zA-Z0-9]', '-', title).lower()[:30]}"
        try:
            repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=source_branch.commit.sha)
        except Exception:
            pass # Branch might already exist

        # Create file
        file_path = f"_posts/{new_branch_name}.md"
        commit_message = f"docs: generated draft blog post for {title}"
        repo.create_file(file_path, commit_message, markdown_content, branch=new_branch_name)

        # Create PR
        pr = repo.create_pull(
            title=f"📝 Draft: {title}",
            body="Generated by AI PR-to-Blog automation.",
            head=new_branch_name,
            base="master"
        )
        return pr.html_url

class LLMService:
    def __init__(self, api_key: str):
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel('gemini-1.5-pro')

    def generate_blog_post(self, pr_context: Dict[str, Any], is_review: bool) -> str:
        system_prompt = """
        You are a Staff Software Engineer and Technical Founder. Your writing style is pragmatic, direct, and deeply technical. 
        You do not use marketing fluff, buzzwords, or generic introductions. You write for other senior engineers.
        Do NOT use phrases like "In conclusion", "In this digital era", or "Let's dive in". Be concise. Use Markdown formatting.
        """
        
        if is_review and pr_context["review_comments"]:
            user_prompt = f"""
            I have just completed a Code Review for a team member's Pull Request. Please write a technical blog post focused on "Code Review Learnings" or "Engineering Standards".
            
            PR Title: {pr_context['title']}
            My Review Comments:
            {chr(10).join(pr_context['review_comments'])}
            
            Structure the blog post as follows:
            # [Catchy Title e.g., Code Review: Optimizing Database Queries]
            - **The Context:** What was the original code trying to achieve?
            - **The Anti-Pattern / Issue:** Explain the flaw, inefficiency, or security issue.
            - **The Better Approach:** Explain the feedback I gave and why the new approach is superior.
            - **Takeaway:** A 1-sentence pragmatic rule of thumb.
            """
        else:
            diffs = "\n".join([f"File: {f['filename']}\n{f['patch']}" for f in pr_context['files'][:5]]) # Limit to 5 files to save tokens
            user_prompt = f"""
            I have just merged a Pull Request. Please write a technical blog post draft based on this PR.
            
            PR Title: {pr_context['title']}
            PR Description: {pr_context['body']}
            
            Code Diff Snippets:
            ```diff
            {diffs}
            ```
            
            Structure the blog post as follows:
            # [Catchy, Technical Title]
            - **The Problem:** Briefly explain the technical debt, bug, or feature gap.
            - **The Solution:** Explain the architectural approach taken to solve it.
            - **Under the Hood:** Highlight 1-2 interesting technical snippets from the diff.
            - **Impact:** What does this mean for the system's performance or reliability?
            """
            
        response = self.model.generate_content([system_prompt, user_prompt])
        return response.text

class BlogGenerator:
    def __init__(self, github_token: str, gemini_key: str, portfolio_repo: str):
        self.github_client = GitHubClient(github_token)
        self.llm_service = LLMService(gemini_key)
        self.portfolio_repo = portfolio_repo

    def run(self, repo_name: str, pr_number: int, event_name: str) -> None:
        print(f"Fetching PR context for {repo_name}#{pr_number}...")
        pr_context = self.github_client.get_pr_details(repo_name, pr_number)
        
        is_review = event_name == "pull_request_review"
        print(f"Generating blog post (Is Review: {is_review})...")
        markdown_content = self.llm_service.generate_blog_post(pr_context, is_review)
        
        print("Publishing draft to portfolio repo...")
        pr_url = self.github_client.create_portfolio_pr(self.portfolio_repo, pr_context['title'], markdown_content)
        print(f"Draft successfully created at: {pr_url}")

if __name__ == "__main__":
    github_token = os.environ.get("GITHUB_TOKEN", "")
    gemini_key = os.environ.get("GEMINI_API_KEY", "")
    repo_name = os.environ.get("GITHUB_REPOSITORY", "")
    pr_number = int(os.environ.get("PR_NUMBER", "0"))
    event_name = os.environ.get("GITHUB_EVENT_NAME", "pull_request")
    portfolio_repo = os.environ.get("PORTFOLIO_REPO", "OkayJosh/OkayJosh.github.io")
    
    if github_token and gemini_key and repo_name and pr_number:
        generator = BlogGenerator(github_token, gemini_key, portfolio_repo)
        generator.run(repo_name, pr_number, event_name)
    else:
        print("Missing required environment variables.")
